import localFont from "next/font/local";
import "./globals.css";
import Layout from "../components/layout";
import { ConfigProvider } from "antd";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import ReduxProvider from "./ReduxProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <AntdRegistry>
            <ConfigProvider
              theme={{
                components: {
                  Menu: {
                    itemSelectedBg: "#111",
                    itemSelectedColor: "#0093A7",
                    itemColor: "#FFFFFFBF",
                    itemHoverColor: "#FFFFFFBF",
                    itemActiveBg: "#111",
                  },
                },
              }}
            >
              {/* ToastContainer added here for global accessibility */}
              <ToastContainer position="top-right" autoClose={3000} />
              <Layout>{children}</Layout>
            </ConfigProvider>
          </AntdRegistry>
        </ReduxProvider>
      </body>
    </html>
  );
}
